version: '3.8'
services:
  app:
    image: weather-api-call:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - R2DBC_URL=r2dbc:pool:postgres://host.docker.internal:5432/callweatherapi
      - R2DBC_USER=postgres
      - R2DBC_PASSWORD=1234