server:
  port: 8090

spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/callweatherapi
    username: postgres
    password: 1234

auth:
  validapikey: 6240a723-d269-41c8-9d12-7321d406e72e
  headername: X-API-key

util:
  webclient:
    baseurl: http://localhost:8085/api
    timeout: 2000